# Generated by Django 5.2.7 on 2025-10-09 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProteinSequence",
            fields=[
                (
                    "gene_name",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("sequence", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneExpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample1", models.IntegerField(blank=True)),
                ("sample2", models.IntegerField(blank=True)),
                ("sample3", models.IntegerField(blank=True)),
                ("sample4", models.IntegerField(blank=True)),
                ("sample5", models.IntegerField(blank=True)),
                ("sample6", models.IntegerField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gene_expression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expressions",
                        to="api.proteinsequence",
                    ),
                ),
            ],
        ),
    ]
