
FROM node:20
WORKDIR /app

COPY package*.json ./

RUN npm install --include=dev && \
    npm rebuild rollup --force && \
    npm cache clean --force

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
